---
- name: Install packages and download file
  hosts: fedora_machines
  tasks:
    - name: Install Vim
      become: yes
      dnf:
        name: vim
        state: present

    - name: Install Transmission
      become: yes
      dnf:
        name: transmission
        state: present

    - name: Install Zsh
      become: yes
      dnf:
        name: zsh
        state: present

    - name: Download text file from URL
      become: no
      get_url:
        url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
        dest: "~/install-oh-my-zsh.sh"
        mode: '0755'

    - name: Execute downloaded file with expected input
      become: no
      expect:
        command: ~/install-oh-my-zsh.sh
        responses:
          'Do you want to continue?': 'y'
          'Password:': ' '