---
- name: Install packages and download file
  hosts: fedora_machines
  become: yes
  tasks:
    - name: Install Vim
      dnf:
        name: vim
        state: present

    - name: Install Transmission
      dnf:
        name: transmission
        state: present

    - name: Install Zsh
      dnf:
        name: zsh
        state: present

    - name: Download zsh-installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /etc/install.sh
        mode: '0755'
    
    - name: Execute install.sh
      ansible.builtin.command: /etc/install.sh